# Generated by Django 4.2.13 on 2024-05-19 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import wallet_base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro", models.CharField(db_index=True, max_length=100)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("alias", "alias"), ("cbu", "cbu")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=wallet_base.models.uuid_md5,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "wallet_number",
                    models.CharField(
                        db_index=True,
                        default=wallet_base.models.generate_unique_wallet_number,
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "culture",
                    models.CharField(
                        db_index=True, default="es-ar", max_length=5, null=True
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wallet_base.leadpayment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=wallet_base.models.uuid_md5,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, db_index=True, default=0, null=True
                    ),
                ),
                (
                    "object_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("p", "Pending"),
                            ("a", "Available"),
                            ("e", "Expired"),
                            ("x", "Processed"),
                            ("c", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=1,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("ARS", "Peso - Argentino")],
                        db_index=True,
                        default="ARS",
                        max_length=3,
                    ),
                ),
                ("amount", models.FloatField(db_index=True)),
                (
                    "datetime_available",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "datetime_expiration",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "datetime_added",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wallet_base.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletExtractionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_resolution",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "datetime_request",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("p", "Pending"),
                            ("r", "Processed"),
                            ("e", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=1,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wallet_base.wallettransaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="walletextractionrequest",
            constraint=models.UniqueConstraint(
                fields=("wallet_transaction", "status"),
                name="unique_extraction",
            ),
        ),
    ]
